namespace: habit-dev
frontend:
  image: brandonchongwenjun/habit-frontend:c5b9dd6b69963e12d589277d571055cde98df4fe
  port: 80
habitService:
  image: brandonchongwenjun/habit-service:c5b9dd6b69963e12d589277d571055cde98df4fe
  port: 4000
userService:
  image: brandonchongwenjun/user-service:c5b9dd6b69963e12d589277d571055cde98df4fe
  port: 4001
analytics:
  image: brandonchongwenjun/habit-analytics:c5b9dd6b69963e12d589277d571055cde98df4fe
rabbitmq:
  image: rabbitmq:3-management
  username: guest
  password: guest
  storage: 1Gi
