apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-analytics
  labels:
    app: habit-analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: habit-analytics
  template:
    metadata:
      labels:
        app: habit-analytics
    spec:
      containers:
        - name: analytics
          image: {{ .Values.analytics.image }}
          env:
            - name: SUPABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-supabase
                  key: SUPABASE_URL
            - name: SUPABASE_SERVICE_ROLE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-supabase
                  key: SUPABASE_SERVICE_ROLE_KEY
            - name: RABBITMQ_URL
              value: "amqp://habit-tracker-rabbitmq:5672"
            - name: RABBITMQ_HABIT_EXCHANGE
              value: "habit.events"
