apiVersion: apps/v1
kind: Deployment
metadata:
  name: habit-frontend
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: habit-frontend
  template:
    metadata:
      labels:
        app: habit-frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.frontend.port }}
          env:
            - name: VITE_API_BASE_URL
              value: "/api"
