apiVersion: v1
kind: Service
metadata:
  name: habit-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: habit-service
  ports:
    - port: 4000
      targetPort: {{ .Values.habitService.port }}
      protocol: TCP
