apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts: #The hosts are the domains that the ingress will listen on.
        - habit-tracker.ltu-m7011e-8.se
      secretName: habit-tls #The secretName is the name of the secret that contains the TLS certificate and key.
  rules:
    - host: habit-tracker.ltu-m7011e-8.se
      http:
        paths:
          - path: /api/habits
            pathType: Prefix
            backend:
              service:
                name: habit-service
                port:
                  number: 4000
          - path: /api/leaderboard
            pathType: Prefix
            backend:
              service:
                name: habit-service
                port:
                  number: 4000
          - path: /api/users
            pathType: Prefix
            backend:
              service:
                name: user-service
                port:
                  number: 4001
          - path: /grafana
            pathType: Prefix
            backend:
              service:
                name: habit-tracker-grafana
                port:
                  number: 3000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: habit-frontend
                port:
                  number: 80
