apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-rabbitmq-pvc
  labels:
    app: habit-rabbitmq
spec:
  accessModes:
    - ReadWriteOnce  # Only one pod can mount at a time
  resources:
    requests:
      storage: {{ .Values.rabbitmq.storage | default "1Gi" }}  # Default 1GB