apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-supabase
type: Opaque
stringData:
  SUPABASE_URL: "https://zbwiwcgmpniraxdvejfq.supabase.co"
  SUPABASE_SERVICE_ROLE_KEY: "REPLACE_ME_IN_REAL_CLUSTER"
  SUPABASE_JWT_SECRET: "REPLACE_ME_IN_REAL_CLUSTER"
