apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-supabase
type: Opaque
stringData:
  SUPABASE_URL: "https://zbwiwcgmpniraxdvejfq.supabase.co"
  SUPABASE_SERVICE_ROLE_KEY: "enter your service role key here"
  SUPABASE_JWT_SECRET: "enter your jwt secret here"
