name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 #Downloads the entire contents of your Git repository onto the runner.

      - name: Use Node.js
        uses: actions/setup-node@v4 #Sets up the Node.js environment on the runner.
        with:
          node-version: 22 #Specifies the version of Node.js to use.

      - name: Install dependencies
        run: npm install #Installs the dependencies for the project.

      - name: Build frontend
        run: npm run build #Builds the frontend of the project.

      - name: Run frontend tests
        run: npm test #Runs the tests for the frontend of the project.

  habit-service:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: habit-service
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 #Downloads the entire contents of your Git repository onto the runner.

      - name: Use Node.js
        uses: actions/setup-node@v4 #Sets up the Node.js environment on the runner.
        with:
          node-version: 22 #Specifies the version of Node.js to use.

      - name: Install dependencies
        run: npm install #Installs the dependencies for the project.

      - name: Run habit-service tests
        run: npm test #Runs the tests for all test files under habit-service/tests/.
        env:
          NODE_ENV: test #Sets the environment variable for the project.

  user-service:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: user-service
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      # - name: Run user-service tests
      #   run: npm test 
      #   env:
      #     NODE_ENV: test
      # Uncomment above when you have tests in user-service

  analytics-service:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: analytics-service
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      # - name: Run analytics-service tests
      #   run: npm test
      #   env:
      #     NODE_ENV: test
      # Uncomment above when you have tests in analytics-service
